[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bitdsm_solana = "FSz1FrDprWyWHCiqBLK8g9Zs4w1ZQAkMQfFk1obrG3iP"

[registry]
url = "https://api.apr.dev"
# url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_timeout = 10000
startup_wait = 10000
